name: soccer_benchmarking
version: "1.0.0"
config-version: 2

profile: soccer_benchmarking

model-paths: ["models"]

models:
  soccer_benchmarking:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
